FROM nvidia/cuda:12.8.0-devel-ubuntu22.04

# Install CMake and necessary tools
RUN apt-get update && apt-get install -y \
    vim \
    build-essential \
    cmake \
    libopenmpi-dev \
    openmpi-bin

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
